apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: invest-project-cservice-eu-central2-webscraping-daily
  labels:
    cloud.googleapis.com/location: europe-central2
  annotations:
    run.googleapis.com/ingress: internal
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "1"
    spec:
      containerConcurrency: 1
      timeoutSeconds: 600
      serviceAccountName: sa-cr-cf-invoker@projekt-inwestycyjny.iam.gserviceaccount.com
      containers:
      - image: europe-central2-docker.pkg.dev/projekt-inwestycyjny/cloud-run-source-deploy/invest-project-cservice-eu-central2-webscraping-daily:latest
        resources:
          limits:
            cpu: 250m
            memory: 512Mi
        ports:
        - containerPort: 8080